/**
 * Login
 */
export const USER_AUTHENTICATED = "USER_AUTHENTICATED";
export const SET_USER_DATA = "SET_USER_DATA";

/**
 * Products
 */
export const PRODUCT_FETCHED = "PRODUCT_FETCHED";
export const PRODCUT_ERROR = "PRODUCT_ERROR"
export const ADD_MOTE_PRODUCTS = "ADD_MOTE_PRODUCTS";
export const FILTER_APPLIED = 'FILTER_APPLIED';

/**
 * Collections
 */
export const COLLECTION_FETCHED = "COLLECTION_FETCHED";
export const COLLECTION_ERROR = "COLLECTION_ERROR";
export const NEW_ARRIVALS_FETCHED = "NEW_ARRIVALS_FETCHED";

/**
 * Cart
 */
export const ADD_TO_CART = 'ADD_TO_CART';
export const SET_TO_CART_ITEMS = 'SET_TO_CART_ITEMS';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY'; 
export const ADD_TO_TOTAL_ITEMS = 'ADD_TO_TOTAL_ITEMS';
export const REMOVE_FROM_TOTAL_ITEMS = 'REMOVE_FROM_TOTAL_ITEMS';

/**
 * Wishlist
 */
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';
export const SET_TO_WISHLIST_ITEMS = 'SET_TO_WISHLIST_ITEMS';

/**
 * Account
 */
export const INFO_FETCHED = "INFO_FETCHED";
export const INFO_UPDATED = "INFO_UPDATED";
export const ORDERS_FETCHED = "ORDERS_FETCHED";
export const ADDRESSES_FETCHED = "ADDRESSES_FETCHED";
export const ADDRESS_ADDED = "ADDRESS_ADDED";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";

/**
 * Checkout
 */
export const EMPTY_CHECKOUT_CREATED = "EMPTY_CHECKOUT_CREATED";
export const CHECKOUT_UPDATED = "CHECKOUT_UPDATED";
export const FETCHED_SHIPPING_RATES = "FETCHED_SHIPPING_RATES";
export const VAULT_ID_GENERATED = "VAULT_ID_GENERATED";
export const CHECKOUT_COMPLETED = "CHECKOUT_COMPLETED";
